version: '3.6'
services:
    database:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: '${DATABASE_NAME}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_USER: '${DATABASE_USER}'
        volumes:
            - database_data:/var/lib/postgresql/data:rw
    webapp:
        build:
            context: ./config/
            dockerfile: php/Dockerfile
        volumes:
            - ./app/${INTERNAL_APP_DIRECTORY}:/usr/src/app
    nginx:
        image: nginx:latest
        restart: on-failure
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app/${INTERNAL_APP_PUBLIC_DIRECTORY}:/usr/src/app
        depends_on:
            - webapp
    adminer:
        image: adminer
        restart: on-failure
        ports:
          - "8080:8080"
volumes:
    database_data:
